spring:
  application:
    name: yph_api_client
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic
      okhttp:
        enabled: true

json-placeholder:
  url: https://jsonplaceholder.typicode.com/
